server:
  port: 7777
  servlet:
    context-path: /yang
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/session1?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    password: 123456
    username: root
  redis:
    host: 192.168.10.129
    port: 6382
    password: 123456
    jedis:
      pool:
        min-idle: 10
        max-active: 100
        max-idle: 100
    timeout: 5000
    database: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.yang.session.pojo
  mapper-locations: classpath:Mapper/*.xml